apiVersion: v1
kind: Service
metadata:
  name: nodejs-rest-api-service
  labels:
    app: nodejs-rest-api
spec:
  type: NodePort
  selector:
    app: nodejs-rest-api
  ports:
  - port: 80
    targetPort: 3000
    # NodePort allows accessing the service on VM_IP:30001
    nodePort: 30001
    protocol: TCP
